### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by brunomarquesconte** [andersao/moip-assinaturas-php#1]
Estou fazendo a implementação, esta dando seguinte erro:

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: 401' in /home/freelasi/public_html/moip/vendor/guzzlehttp/guzzle/src/Middleware.php:69 Stack trace: #0 /home/freelasi/public_html/moip/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #1 /home/freelasi/public_html/moip/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #2 /home/freelasi/public_html/moip/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #3 /home/freelasi/public_html/moip/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run() #4 /home/freelasi/public_html/moip/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick() #5 /home/freelasi/public_html/moip/vendor/guzzlehttp/promises/src/Promise.php(246): Guz in /home/freelasi/public_html/moip/vendor/guzzlehttp/guzzle/src/Middleware.php on line 69

**Meu codigo:**

require '../vendor/autoload.php';

use Prettus\Moip\Subscription\MoipClient;
use Prettus\Moip\Subscription\Api;

$client = new MoipClient("8HXGCUFNB3FCG7GANATJV9JS6J721SL9","VGMNHQKJOGK9LNSTDQI7K5BLHDXSERC0XUAJSTZS");

$api = new Api($client);

**Comment by brunorbarroso** [comment]
Olá, @brunomarquesconte. Tudo bem?

Cara, também estou utilizando esse projeto. O que eu acho que pode ser o motivo do erro:
Por default, quando você cria uma instância da class **MoipClient**, ele define que você está usando a API de **Produção**. Caso deseje utilizar API da **Sandbox** (acredito que seja sua necessidade), é só passar um terceiro parâmetro no momento de instanciar.
Ex:  `$client = new MoipClient("TOKEN","KEY", MoipClient::SANDBOX);`

Abraços.
